name: rikulo_geoip
version: 0.5.0
description: >
  Rikulo GeoIP is a Dart client bridge to GeoIP service provided by smart-ip.net.
authors:
- Henri Chen <henrichen@rikulo.org>
homepage: http://rikulo.org
dependencies:
  js: '0.0.7'
  rikulo_commons:
